name: record_android
description: Android specific implementation for record package called by record_platform_interface.
version: 1.2.6
homepage: https://github.com/qiaovc/record/tree/master/record_android

environment:
  sdk: ^3.3.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface:
    path: ../record_platform_interface/

flutter:
  plugin:
    implements: record
    platforms:
      android:
        package: com.qiaovc.record
        pluginClass: RecordPlugin
